print("System Failure Imminent!")
print("System reboot has been initiated...")
print()
print("...rebooting sensory system")
print("...rebooting sensory system")
print("...rebooting sensory system")
print()
print("System online.")