lives=int(input("Please enter the number of lives.\n"))
energy=int(input("please enter the energy level.\n"))
shield=int(input("please enter the shield level.\n"))
print("Health has been set")
print("lives:",end='')
print("\u2764\t"*lives)
print("energy:",end='')
print("\u2666\t"*energy)
print("shield:",end='')
print("\u2666\t"*shield)
